# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Henrique C. Costa
title: Mestre em Economia | Cientista de Dados - R
email: henrique@outlook.sg
#website: https://datametricks.github.io/hcostax.github.io/

# Social links
twitter_username: hcostax
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: hcostax
linkedin_username: henriqccosta
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/foto.jpg
about_content: | # this will include new lines to allow paragraphs
  Olá, meu nome é Henrique e sou Mestre em Economia pela Faculdade de Economia - UFMT e Economista registrado pelo Corecon-MT: 2088. 
  Apaixonado pela Ciência Econômica, jovem e com muita sede de conhecimento. Tenho "preferencia revelada" por microeconomia e microeconometria.
  Curioso, entusiasta e estudante de Ciência de Dados, gosto particularmente da linguagem de programação em R e sou usuário de RMarkDown/LaTeX.
  
  Tenho um projeto incubado, o Análise Real (Research), atualmente residente em Cuiabá - MT, Brasil.
  Se quiser entrar em contato, sinta-se à vontade para dizer olá por meio de qualquer um das redes sociais acima.


 Eu sou mais experiente em: <mark> Fazendo café </mark> e <mark> Comendo pizza </mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
 Juntamente com meus interesses em Economia e Ciência de Dados, alguns de meus outros interesses e hobbies são:
   - Ler Mangás
   - [Jogar DotA 2](https://steamcommunity.com/id/quonli)
   - Música classica (A. Vivaldi)
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
